title: My Blog!
author: Derek Rodriguez
email: drodriguez910@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog for Data Science Projects.

# social links
twitter_username: tastybrisket10 # DO NOT include the @ character, or else the build will fail!
github_username:  drodriguez910 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
